apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-beproject
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: beproject
    repoURL: https://arthurf-java.github.io/helm-be/
    targetRevision: 1-dev-b172009b12fd493696b70469a328f9697ac63919
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Replace=true
