apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-beproject
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: beproject
    repoURL: https://arthurf-java.github.io/helm-be/
    targetRevision: 1-dev-f098efbcb1be40376d8bb00d6d57eadeee3c6621
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Replace=true
