apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-beproject
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: beproject
    repoURL: https://arthurf-java.github.io/helm-be/
    targetRevision: 1-dev-b7397be7f6f4e15a4f04cef2bdebac5c5eef8d48
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Replace=true
