apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-beproject
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: beproject
    repoURL: https://arthurf-java.github.io/helm-be/
    targetRevision: 1-dev-c4ee03b5d19706ed2861c517b6e78cb0ee65d526
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Replace=true
