apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-prod
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: postgresql
    helm:
      parameters:
        - name: namespace
          value: prod
    repoURL: https://arthurf-java.github.io/helm-tools/
    targetRevision: 14.5-config-map