apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-beproject
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: beproject
    repoURL: https://arthurf-java.github.io/helm-be/
    targetRevision: 1-prod-9f624ed6c8167d55464de0cd28e79f270c7a53fa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Replace=true
