apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-beproject
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: beproject
    repoURL: https://arthurf-java.github.io/helm-be/
    targetRevision: 1-prod-a832614e5671f9208e53937a6670993dfdd4704a
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Replace=true
