apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-beproject
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: beproject
    repoURL: https://arthurf-java.github.io/helm-be/
    targetRevision: 1-prod-4fcb258473c34a2f7cb7fb3ef998afc7f484f00b
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Replace=true
