---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://arthurf-java.github.io/helm-tools/
    chart: postgresql
    targetRevision: "14.5"
    helm:
      values: |
        auth:
          postgresPassword:
            secretKeyRef:
              name: dev-secret
              key: postgresql-password
          database:
            secretKeyRef:
              name: dev-secret
              key: postgresql-database
          username:
            secretKeyRef:
              name: dev-secret
              key: postgresql-username
        persistence:
          enabled: true
          size: 4Gi
        namespace: dev-env
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: {}


