name: Trigger ArgoCD Sync

#on:
#  push:
#    branches:
#      - main
#    paths:
#      - 'dev/**'

on:
  workflow_dispatch:
    inputs:
      button_name:
        description: 'Setup KinD'

jobs:
  trigger-argocd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update /etc/hosts
        run: |
          echo "178.124.206.53	argocd.k8s-15.sa" | sudo tee -a /etc/hosts
          cat /etc/hosts

      - name: Trigger ArgoCD Sync
        env:
          ARGOCD_SERVER: argocd.k8s-15.sa
          ARGOCD_TOKEN: ${{ secrets.ARGOCD_TOKEN }}
          ARGOCD_APP_NAME: dev-be-root
        run: |
          # Trigger ArgoCD sync using the API
          curl -X POST \
            -H "Authorization: Bearer $ARGOCD_TOKEN" \
            -H "Content-Type: application/json" \
            "$ARGOCD_SERVER/api/v1/applications/$ARGOCD_APP_NAME/sync" \
            -d '{}'

#          ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
#          ARGOCD_TOKEN: ${{ secrets.ARGOCD_TOKEN }}
#          ARGOCD_APP_NAME: ${{ secrets.ARGOCD_APP_NAME }}