name: Trigger ArgoCD Sync

#on:
#  push:
#    branches:
#      - main
#    paths:
#      - 'dev/**'

on:
  workflow_dispatch:
    inputs:
      button_name:
        description: 'Setup KinD'

jobs:
  trigger-argocd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update /etc/hosts
        run: |
          echo "178.124.206.53	argocd.k8s-15.sa" | sudo tee -a /etc/hosts

      - name: Run YAML to Github Output Action
        id: yaml-output
        uses: christian-ci/action-yaml-github-output@v2
        with:
          file_path: dev/application.yaml
          main_key: spec

      - name: Ping helm repo it returns 200
        run: |
          echo "${{ steps.yaml-output.outputs.repoURL }}dev/${{ steps.yaml-output.outputs.chart }}-${{ steps.yaml-output.outputs.targetRevision }}"
          url="${{ steps.yaml-output.outputs.repoURL }}dev/${{ steps.yaml-output.outputs.chart }}-${{ steps.yaml-output.outputs.targetRevision }}".tgz
          max_attempts=10
          attempt=1
          sleep_duration=2

          while [ $attempt -le $max_attempts ]; do
            echo "Attempt $attempt: Pinging $url..."
            response_code=$(curl -s -o /dev/null -w "%{http_code}" "$url")

            if [ "$response_code" -eq 200 ]; then
              echo "Success: Received HTTP 200!"
              exit 0
            else
              echo "Failed: Received HTTP $response_code. Retrying in $sleep_duration seconds..."
              sleep $sleep_duration
              attempt=$((attempt + 1))
            fi
          done

          echo "Error: Max attempts reached. Exiting."
          exit 1

      - name: Trigger ArgoCD Sync
        env:
          ARGOCD_SERVER: ${{ vars.ARGOCD_SERVER }}
          ARGOCD_TOKEN: ${{ secrets.ARGOCD_TOKEN }}
          ARGOCD_APP_NAME: ${{ vars.ARGOCD_DEV_APP_NAME }}
        run: |
          response_code=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
            -H "Authorization: Bearer $ARGOCD_TOKEN" \
            -H "Content-Type: application/json" \
            "$ARGOCD_SERVER/api/v1/applications/$ARGOCD_APP_NAME/sync" \
            -d '{}')

          if [ "$response_code" -ne 200 ]; then
            echo "Error: ArgoCD sync failed with HTTP status code $response_code"
            exit 1
          else
            echo "ArgoCD sync triggered successfully"
          fi