name: Prod Actions

on:
  push:
    branches:
      - main
    paths:
      - 'prod/**'

#on:
#  workflow_dispatch:
#    inputs:
#      button_name:
#        description: 'Setup KinD'

jobs:
  trigger-argocd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update /etc/hosts
        run: |
          echo "178.124.206.53	argocd.k8s-15.sa" | sudo tee -a /etc/hosts

      - name: Run YAML to Github Output Action
        id: yaml-output
        uses: christian-ci/action-yaml-github-output@v2
        with:
          file_path: prod/application.yaml
          main_key: spec

      - name: Trigger ArgoCD Sync
        env:
          ARGOCD_SERVER: ${{ vars.ARGOCD_SERVER }}
          ARGOCD_TOKEN: ${{ secrets.ARGOCD_TOKEN }}
          ARGOCD_APP_NAME: ${{ vars.ARGOCD_PROD_APP_NAME }}
        run: |
          response_code=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
            -H "Authorization: Bearer $ARGOCD_TOKEN" \
            -H "Content-Type: application/json" \
            "$ARGOCD_SERVER/api/v1/applications/$ARGOCD_APP_NAME/sync" \
            -d '{}')

          if [ "$response_code" -ne 200 ]; then
            echo "Error: ArgoCD sync failed with HTTP status code $response_code"
            exit 1
          else
            echo "ArgoCD sync triggered successfully"
          fi
      - name: Slack Notification
        if: success()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: afon-check
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: 'Post Content :rocket:'
          SLACK_TITLE: 'ArgoCD Sync PROD is done for image ${{ steps.yaml-output.outputs.targetRevision }}'
          SLACK_USERNAME: fonichkin
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      - name: Slack Notification
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: afon-check
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_TITLE: 'ArgoCD Sync PROD is failed for image ${{ steps.yaml-output.outputs.targetRevision }}'
          SLACK_USERNAME: fonichkin
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}