name: Test Actions

on:
  push:
    branches:
      - main
    paths:
      - 'test/**'

#on:
#  workflow_dispatch:
#    inputs:
#      button_name:
#        description: 'Setup KinD'

jobs:
  trigger-argocd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update /etc/hosts
        run: |
          echo "178.124.206.53	argocd.k8s-15.sa" | sudo tee -a /etc/hosts

      - name: Trigger ArgoCD Sync
        env:
          ARGOCD_SERVER: ${{ vars.ARGOCD_SERVER }}
          ARGOCD_TOKEN: ${{ secrets.ARGOCD_TOKEN }}
          ARGOCD_APP_NAME: ${{ vars.ARGOCD_TEST_APP_NAME }}
        run: |
          response_code=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
            -H "Authorization: Bearer $ARGOCD_TOKEN" \
            -H "Content-Type: application/json" \
            "$ARGOCD_SERVER/api/v1/applications/$ARGOCD_APP_NAME/sync" \
            -d '{}')

          if [ "$response_code" -ne 200 ]; then
            echo "Error: ArgoCD sync failed with HTTP status code $response_code"
            exit 1
          else
            echo "ArgoCD sync triggered successfully"
          fi